global:
  scrape_interval: 30s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: pushgateway
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus-pushgateway:9091
  - job_name: mysql
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - mysql-exporter:9104
  - job_name: todos_api
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 10.0.0.163:8080