groups:
- name: DatabaseAlerts
  rules:
    - alert: InstanceDown
      expr: mysql_up{job="mysql"} < 1
      for: 10s
      labels:
        severity: low
      annotations:
        summary: 'Alert with low severity.'

    - alert: InstanceDownCritical
      expr: mysql_up{job="mysql"} < 1
      for: 10s
      labels:
        severity: high
      annotations:
        summary: 'Alert with high severity.'
