CREATE TABLE IF NOT EXISTS todos (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NULL,
    description TEXT NULL,
    done enum('false', 'true') DEFAULT 'false',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB
DEFAULT CHARACTER SET = utf8;
